### ISSUE TITLE
Translation Module: tune gpt model for domain adaptation

### ISSUE THREAD

**Issue by yichen14** [pigeonai-org/ViDove#6]
- [x] Use OpenAI's RAG or our own RAG to have a GPTs on different domain
- [x] Use Open AI RAG API interface
- [] Data Prepration

**Comment by yichen14** [comment]
Data pattern:
- dictionary(same as dicts in our repo)
    - many-to-many
- definition(words -> def)
- examples(translation examples)

**Comment by JiaenLiu** [comment]
Some questions about assistant (RAG):

Currently the adaption of new api format is done, however some tasks and problems still need to be handled.

1. Assistant Creation, since one assistant can be setup for one domain, when and where to create the assistant.
2. Assistant management.
3. Support files mannagement for the RAG, e.g. allow user to upload the files to chosen assistant.

@yichen14 @Chester-Lin-Qiming

**Comment by yichen14** [comment]
Can we test on this Vidove-SC2 first? @JiaenLiu 
ass_id: asst_v1cEwYXexhfmkPEYtISyIjYI

**Comment by JiaenLiu** [comment]
This assistant is hard coded in the code. @yichen14

**Comment by yichen14** [comment]
@JiaenLiu please investigate system prompt for assistant API
@Chester-Lin-Qiming please help us debug test cases

Thank you for the great work!
